language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
 - phpunit --coverage-clover=coverage.clover --configuration ./phpunit.xml.dist ./tests

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 8afb9574bf8d4fb355b569361b043087b45edde3eb6eb96cdc2fe9e0ddf64330